import fs from "fs";
import path from "path";

const NETSCAPE_HEADER = `# Netscape HTTP Cookie File
# This file is generated by yt-dlp-webui. Do not edit manually.

`;

/**
 * Get the cookies directory path from config.
 */
export function getCookiesDir(): string {
  try {
    const configPath = path.resolve("webui_config.json");
    if (fs.existsSync(configPath)) {
      const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      if (config.cookies_path && typeof config.cookies_path === "string") {
        // Store per-site files in a subdirectory next to the main cookies file
        return path.join(path.dirname(config.cookies_path), "cookies");
      }
    }
  } catch {}
  return "/share/yt-dlp-webui/cookies";
}

/**
 * Get the merged cookies file path (what yt-dlp uses).
 */
export function getMergedCookiesPath(): string {
  try {
    const configPath = path.resolve("webui_config.json");
    if (fs.existsSync(configPath)) {
      const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      if (config.cookies_path && typeof config.cookies_path === "string") {
        return config.cookies_path;
      }
    }
  } catch {}
  return "/share/yt-dlp-webui/cookies.txt";
}

/**
 * List all configured cookie sites.
 */
export function listCookieSites(): Array<{
  domain: string;
  path: string;
  size: number;
  lastModified: string;
}> {
  const cookiesDir = getCookiesDir();
  if (!fs.existsSync(cookiesDir)) return [];

  try {
    const files = fs.readdirSync(cookiesDir).filter((f) => f.endsWith(".txt"));
    return files.map((f) => {
      const filePath = path.join(cookiesDir, f);
      const stat = fs.statSync(filePath);
      return {
        domain: f.replace(/\.txt$/, ""),
        path: filePath,
        size: stat.size,
        lastModified: stat.mtime.toISOString(),
      };
    });
  } catch {
    return [];
  }
}

/**
 * Convert a raw Cookie header string to Netscape cookie format.
 *
 * Accepts formats:
 * - "name1=value1; name2=value2" (standard Cookie header)
 * - "name1=value1\nname2=value2" (one per line)
 * - Lines starting with # are treated as comments
 */
export function parseCookieHeader(
  domain: string,
  cookieString: string,
): string {
  let output = NETSCAPE_HEADER;
  const lines = cookieString
    .split(/[\n\r]+/)
    .map((l) => l.trim())
    .filter((l) => l.length > 0 && !l.startsWith("#"));

  for (const line of lines) {
    // Handle "Cookie: ..." prefix if present
    const cleanLine = line.toLowerCase().startsWith("cookie:")
      ? line.slice(7).trim()
      : line;

    // Split by semicolons to get individual name=value pairs
    const pairs = cleanLine.split(";").map((p) => p.trim());

    for (const pair of pairs) {
      const eqIdx = pair.indexOf("=");
      if (eqIdx === -1) continue;

      const name = pair.slice(0, eqIdx).trim();
      const value = pair.slice(eqIdx + 1).trim();

      if (!name) continue;

      // Netscape format: domain \t flag \t path \t secure \t expiration \t name \t value
      // - domain with leading dot = domain-wide
      // - flag TRUE = domain match
      // - path / = all paths
      // - secure FALSE = not required
      // - expiration 0 = session cookie
      output += `.${domain}\tTRUE\t/\tFALSE\t0\t${name}\t${value}\n`;
    }
  }

  return output;
}

/**
 * Detect the domain from a Netscape cookie file content.
 * Looks for domain entries like ".youtube.com" or "youtube.com".
 */
export function detectDomainsFromContent(content: string): string[] {
  const domains = new Set<string>();
  const lines = content.split("\n");

  for (const line of lines) {
    if (line.startsWith("#") || line.trim() === "") continue;
    const parts = line.split("\t");
    if (parts.length >= 7) {
      // First field is domain, may start with "."
      const domain = parts[0].replace(/^\./, "");
      if (domain) domains.add(domain);
    }
  }

  return Array.from(domains);
}

/**
 * Save a per-site cookie file.
 */
export function saveSiteCookies(
  domain: string,
  content: string,
): { path: string; size: number } {
  const cookiesDir = getCookiesDir();
  if (!fs.existsSync(cookiesDir)) {
    fs.mkdirSync(cookiesDir, { recursive: true });
  }

  const safeName = domain.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 100);
  const filePath = path.join(cookiesDir, `${safeName}.txt`);

  // Ensure it has the Netscape header
  let finalContent = content;
  if (
    !content.includes("# Netscape HTTP Cookie File") &&
    !content.includes("# http://curl.haxx.se/rfc/cookie_spec.html")
  ) {
    finalContent = NETSCAPE_HEADER + content;
  }

  fs.writeFileSync(filePath, finalContent, "utf-8");
  const stat = fs.statSync(filePath);
  return { path: filePath, size: stat.size };
}

/**
 * Delete a per-site cookie file.
 */
export function deleteSiteCookies(domain: string): boolean {
  const cookiesDir = getCookiesDir();
  const safeName = domain.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 100);
  const filePath = path.join(cookiesDir, `${safeName}.txt`);

  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    return true;
  }
  return false;
}

/**
 * Merge all per-site cookie files into the merged cookies file
 * that yt-dlp uses via --cookies.
 */
export function mergeAllCookies(): {
  mergedPath: string;
  siteCount: number;
  totalSize: number;
} {
  const cookiesDir = getCookiesDir();
  const mergedPath = getMergedCookiesPath();

  let mergedContent = NETSCAPE_HEADER;
  let siteCount = 0;
  let totalSize = 0;

  if (fs.existsSync(cookiesDir)) {
    const files = fs
      .readdirSync(cookiesDir)
      .filter((f) => f.endsWith(".txt"))
      .sort();

    for (const file of files) {
      const filePath = path.join(cookiesDir, file);
      try {
        const content = fs.readFileSync(filePath, "utf-8");
        // Skip the header from individual files, just get the cookie lines
        const lines = content
          .split("\n")
          .filter(
            (l) =>
              !l.startsWith("# Netscape") &&
              !l.startsWith("# This file") &&
              l.trim().length > 0,
          );
        if (lines.length > 0) {
          mergedContent += `\n# --- Cookies from: ${file.replace(/\.txt$/, "")} ---\n`;
          mergedContent += lines.join("\n") + "\n";
          siteCount++;
          totalSize += Buffer.byteLength(lines.join("\n"));
        }
      } catch (e) {
        console.error(`Failed to read cookie file ${file}:`, e);
      }
    }
  }

  // Ensure the merged file's directory exists
  const mergedDir = path.dirname(mergedPath);
  if (!fs.existsSync(mergedDir)) {
    fs.mkdirSync(mergedDir, { recursive: true });
  }

  fs.writeFileSync(mergedPath, mergedContent, "utf-8");
  return { mergedPath, siteCount, totalSize };
}
